Clinic_Management_System/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('patient.urls')),
    path('', include('django.contrib.auth.urls'))
]

patient/urls.py
from django.urls import path
from . import views, views_doc

app_name = "patient"

urlpatterns = [
    path('', views.index, name="index"),
    # path('list', views.patient_list, name="list"),
    path('list/', views.PatientListView.as_view(), name="patient_list"),
    path('search', views.search, name="search"),
    # path('detail/<int:pk>', views.PatientDetailView.as_view(), name="patient_detail"),
    path('patients/detail/<int:patient_id>', views.patient_detail, name="patient_detail"),
    path('patients/add', views.patient_create, name="add"),
    path('patients/update/<int:patient_id>', views.patient_update, name="update"),
    path('patients/history/<int:patient_id>', views.patient_history, name="history"),
    # path('patients/update/<int:pk>', views.PatientUpdateView.as_view(), name="update"),
    path('patients/delete/<int:pk>', views.PatientDeleteView.as_view(), name="delete"),
    
    path('patients/select_appointment/', views.select_appointment, name="select_appointment"),
    path('patients/delete_appointment/', views.delete_appointment, name="delete_appointment"),
    path('appointment/', views.appointment_list, name="appointment"),
    path('patients/appointment/update/<int:appointment_id>', views.appointment_update, name="appointment_update"),
    
    path('patients/history/update/<int:history_id>', views.history_update, name="history_update"),
    
    path('doctors/list/', views_doc.DoctorListView.as_view(), name="doctor_list"),
    path('doctors/add', views_doc.doctor_create, name="doctor_add"),
    path('doctors/update/<int:doctor_id>', views_doc.doctor_update, name="doctor_update"),
    
    path('patients/history/pdf/<int:patient_id>', views.generatePdf, name="pdf_history"),
    # path('patients/history/pdf/<int:patient_id>', views.GeneratePdf.as_view(), name="pdf_history"),

]

patient/forms.py
from django import forms
from datetime import datetime, timedelta
from .models import CHOICES, SUB_CITY_CHOICES, Patient, Appointment, History, Doctor
from django.forms.fields import Field
from crispy_forms.layout import Layout
from crispy_forms.helper import FormHelper


class DateInput(forms.DateInput):
    input_type = 'date'


class PatientForm(forms.ModelForm):
    firstname = forms.CharField(label="First Name")
    surname = forms.CharField(label="Sur Name", required=False)
    middlename = forms.CharField(label="Middle Name", required=False)
    gender = forms.ChoiceField(choices=CHOICES, required=False)
    age = forms.FloatField(label="Age", required=False)
    phone = forms.IntegerField(label="Phone", required=False)

    kebele = forms.IntegerField(label="Kebele", required=False)
    woreda = forms.IntegerField(label="Woreda", required=False)
    sub_city = forms.ChoiceField(label="Subcity",
                                 choices=SUB_CITY_CHOICES,
                                 required=False)

    class Meta:
        model = Patient
        fields = [
            'firstname', 'surname', 'middlename', 'gender', 'age', 'phone',
            'kebele', 'woreda', 'sub_city'
        ]

    def clean(self):
        super(PatientForm, self).clean()

        age = self.cleaned_data.get('age')
        kebele = self.cleaned_data.get('kebele')
        woreda = self.cleaned_data.get('woreda')
        phone = self.cleaned_data.get('phone')

        if age != None and age < 0:
            self._errors['age'] = self.error_class(['Minimum Age must be 0'])
        if kebele != None and kebele < 1:
            self._errors['kebele'] = self.error_class(
                ['Kebele must be greater than 1'])
        if woreda != None and woreda < 1:
            self._errors['woreda'] = self.error_class(
                ['Woreda must be greater than 1'])

        if phone != None and phone < 1:
            self._errors['phone'] = self.error_class(
                ['Phone Number is not valid'])


class HistoryForm(forms.ModelForm):
    history = forms.CharField(label="History and Physical Examination",
                              required=False,
                              widget=forms.Textarea(attrs={
                                  'rows': 5,
                                  'cols': 40
                              }))
    doctor = forms.ChoiceField(
        label="Doctor",
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = History
        fields = ['history']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['doctor'].choices = [(doctor.id,
                                          f'{doctor.firstname} {doctor.surname}')
                                         for doctor in Doctor.objects.all()]


class AppointmentForm(forms.ModelForm):
    # patient = forms.CharField(label="First Name")

    date = forms.DateField(
        label="Appointment",
        widget=DateInput(
            attrs={"min": datetime.now().date().strftime("%Y-%m-%d"), 'id':'assignedDoctor'}),
        required=False)

    class Meta:
        model = Appointment
        fields = ['date', 'doctor']


class DoctorForm(forms.ModelForm):
    firstname = forms.CharField(label="First Name")
    surname = forms.CharField(label="Sur Name", required=False)
    middlename = forms.CharField(label="Middle Name", required=False)
    specialised = forms.CharField(label="Specialised in", required=False)

    phone = forms.IntegerField(label="Phone", required=False)


    class Meta:
        model = Doctor
        fields = [
            'firstname', 'surname', 'middlename', 'phone', 'specialised'
        ]

    # appointment = forms.DateField(
    #     label="Appointment",
    #     widget=DateInput(
    #         attrs={"min": datetime.now().date().strftime("%Y-%m-%d")}),
    #     required=False)

patient/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse, redirect, get_object_or_404
from django.http import JsonResponse, HttpResponse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import json
from .forms import PatientForm, AppointmentForm, HistoryForm
from .models import Patient, Appointment, History, Doctor
import datetime
from django.http import HttpResponse
from django.views.generic import View

from .utils import render_to_pdf


@login_required()
def index(request):
    return render(request, 'patient/index.html', {})


class PatientListView(LoginRequiredMixin, ListView):
    template_name = 'patient/list.html'
    model = Patient
    context_object_name = 'patients'
    paginate_by = 100


class PatientDetailView(LoginRequiredMixin, DetailView):
    template_name = 'patient/detail.html'
    model = Patient
    context_object_name = 'patient'


@login_required()
def patient_detail(request, patient_id):
    return render(
        request, 'patient/detail.html', {
            'patient': Patient.objects.get(pk=patient_id),
            'histories': History.objects.filter(patient=patient_id),
            'doctors': Doctor.objects.all(),
            'appointments': Appointment.objects.filter(patient=patient_id)
        })


@login_required()
def search(request):
    if request.GET:
        search_term = request.GET['search_term']
        context = {
            "search_term":
            search_term,
            "patients":
            Patient.objects.filter(
                Q(card_number__icontains=search_term)
                | Q(firstname__icontains=search_term)
                | Q(surname__icontains=search_term)
                | Q(middlename__icontains=search_term)
                | Q(gender__icontains=search_term)
                | Q(phone__icontains=search_term)
                | Q(created_date__icontains=search_term)
                # Q(appointment__icontains=search_term)
            )
        }
        if not search_term == "":
            return render(request, 'patient/search.html', context)
        else:
            return HttpResponseRedirect(reverse('patient:index'))


@login_required()
def patient_create(request):
    if request.method == 'POST':
        patient_form = PatientForm(request.POST)

        if patient_form.is_valid():
            firstname = patient_form.cleaned_data['firstname']
            surname = patient_form.cleaned_data['surname']
            middlename = patient_form.cleaned_data['middlename']
            gender = patient_form.cleaned_data['gender']
            age = patient_form.cleaned_data['age']
            phone = patient_form.cleaned_data['phone']

            kebele = patient_form.cleaned_data['kebele']
            woreda = patient_form.cleaned_data['woreda']
            sub_city = patient_form.cleaned_data['sub_city']

            patient = Patient.objects.create(firstname=firstname,
                                             surname=surname,
                                             middlename=middlename,
                                             gender=gender,
                                             age=age,
                                             phone=phone,
                                             kebele=kebele,
                                             woreda=woreda,
                                             sub_city=sub_city,
                                             created_by=request.user,
                                             updated_by=request.user)

            patient.save()

            messages.add_message(request, messages.SUCCESS,
                                 'Patient added successfully!')

            return HttpResponseRedirect(reverse('patient:patient_list'))
        else:
            return render(request, 'patient/add.html',
                          {"patient_form": patient_form})
    return render(request, 'patient/add.html', {"patient_form": PatientForm()})


@login_required()
def patient_update(request, patient_id):
    patient = get_object_or_404(Patient, pk=patient_id)
    patient_form = PatientForm(request.POST or None, instance=patient)

    if patient_form.is_valid():
        patient.save()

        messages.add_message(request, messages.SUCCESS,
                             'Patient data updated successfully!')

        return HttpResponseRedirect(reverse('patient:patient_list'))
    else:
        return render(request, 'patient/add.html',
                      {"patient_form": patient_form})
    return render(request, 'patient/update.html',
                  {"patient_form": patient_form})


class PatientUpdateView(LoginRequiredMixin, UpdateView):
    model = Patient
    template_name = 'patient/update.html'
    fields = ['firstname', 'surname', 'middlename', 'age', 'gender', 'phone']

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.updated_by = self.request.user
        instance.save()
        messages.success(self.request, 'Patient data updated successfully!')
        return redirect('patient:patient_detail', instance.pk)


class PatientDeleteView(LoginRequiredMixin, DeleteView):
    model = Patient
    template_name = 'patient/delete.html'
    success_url = '../list/'


@login_required()
def patient_history(request, patient_id):
    if request.method == 'POST':
        history_form = HistoryForm(request.POST)

        if history_form.is_valid():
            history = history_form.cleaned_data['history']
            doctor = history_form.cleaned_data['doctor']

            history = History.objects.create(
                history=history,
                doctor=Doctor.objects.get(pk=doctor),
                patient=Patient.objects.get(pk=patient_id))

            history.save()

            messages.add_message(request, messages.SUCCESS,
                                 'History added successfully!')

            return HttpResponseRedirect(
                reverse('patient:patient_detail', args=(patient_id, )))
        else:
            return render(request, 'patient/history.html',
                          {"history_form": history_form})

    return render(request, 'patient/history.html',
                  {"history_form": HistoryForm()})


@login_required()
def history_update(request, history_id):
    history = get_object_or_404(History, pk=history_id)
    history_form = HistoryForm(request.POST or None, instance=history)

    if history_form.is_valid():
        history.save()

        messages.add_message(request, messages.SUCCESS,
                             'History updated successfully!')

        return HttpResponseRedirect(
            reverse('patient:patient_detail', args=(history.patient.id, )))
    else:
        return render(request, 'patient/history.html',
                      {"history_form": history_form})
    return render(request, 'patient/history.html',
                  {"history_form": history_form})


@login_required()
def appointment_update(request, appointment_id):
    appointment = get_object_or_404(Appointment, pk=appointment_id)
    appointment_form = AppointmentForm(request.POST or None,
                                       instance=appointment)

    if appointment_form.is_valid():
        appointment.save()

        messages.add_message(request, messages.SUCCESS,
                             'Appointment updated successfully!')

        return HttpResponseRedirect(
            reverse('patient:patient_detail', args=(appointment.patient.id, )))
    else:
        return render(request, 'patient/update_appointment.html',
                      {"appointment_form": appointment_form})
    return render(request, 'patient/update_appointment.html',
                  {"appointment_form": appointment_form})


@login_required()
def appointment_list(request):
    return render(
        request, 'patient/appointment.html', {
            "appointment":
            Appointment.objects.all().count(),
            "appointment_today":
            Appointment.objects.filter(date=datetime.date.today()),
            "appointment_tomorrow":
            Appointment.objects.filter(date=datetime.date.today() +
                                       datetime.timedelta(days=1))
        })


@login_required()
def select_appointment(request):
    data = json.loads(request.body)
    patient_id = data["patientId"]
    appointment_date = data["appointmentDate"]
    assigned_doctor = data["assignedDoctor"]
    action = data["action"]

    Appointment.objects.get_or_create(patient=Patient(id=patient_id),
                                      date=appointment_date,
                                      doctor=Doctor(id=assigned_doctor))
    return JsonResponse(
        f'Appointment Booked for {Patient.objects.get(pk=patient_id).firstname} {Patient.objects.get(pk=patient_id).surname}',
        safe=False)


@login_required()
def delete_appointment(request):
    data = json.loads(request.body)
    print('dfdfdf')
    appointment_id = data["appointmentId"]
    print(appointment_id)
    action = data["action"]

    Appointment.objects.filter(id=appointment_id).delete()
    
    return JsonResponse(
        f'Appointment Deleted',
        safe=False)


# def appointment_delete(request, appointment_id):
#     appointment = get_object_or_404(Appointment, id=appointment_id)
#     appointment.delete()
    

def generatePdf(request, patient_id, *args, **kwargs):
    data = {
        'date': datetime.date.today(),
        'patient': Patient.objects.get(pk=patient_id),
        'histories': History.objects.filter(patient=patient_id),
    }
    pdf = render_to_pdf('pdf/pdf_history.html', data)
    return HttpResponse(pdf, content_type='application/pdf')

patient/templates/doctor/doc_add.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block title %} Add
Doctor {% endblock %} {% block content %}

<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Add Doctor</h1>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <form action="" method="post">
    {% csrf_token %}
      <div class="col-md-6 mx-auto">
        <div class="card card-primary" style="min-height: 350px">
          <div class="card-header">
            <h3 class="card-title">Doctor Information</h3>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-sm-4">
                <div class="form-group">
                  {{ doctor_form.firstname | as_crispy_field }}
                </div>
              </div>
              <div class="col-sm-4">
                <div class="form-group">
                  {{ doctor_form.surname | as_crispy_field }}
                </div>
              </div>
              <div class="col-sm-4">
                <div class="form-group">
                  {{ doctor_form.middlename | as_crispy_field }}
                </div>
              </div>
            </div>
            
            <div class="row">
              <div class="col-12">
                <div class="form-group">
                  {{ doctor_form.phone | as_crispy_field }}
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-12">
                <div class="form-group">
                  {{ doctor_form.specialised | as_crispy_field }}
                </div>
              </div>
            </div>

          </div>
        </div>
        <div class="ml-auto w-25 text-right">
      <a href="{% url 'patient:doctor_list' %}" type="button" class="btn btn-secondary">Cancel</a>
      <input type="submit" value="Save" class="btn btn-success" />
    </div>
      </div>
      
    
  </form>
</section>

{% endblock %}

patient/templates/doctor/doc_list.html
{% extends 'base.html' %} {% block title %} Doctors List {% endblock %} 
{%block content %}
<div class="card">
  <div class="card-header">
    <h3 class="card-title">Doctors Record</h3>
  </div>

  <div style="width: 170px; margin-left: auto">
    <a
      href="{% url 'patient:doctor_add' %}"
      class="btn btn-primary text-white mr-3 mt-4"
      ><i class="fas fa-user-plus nav-icon mr-3"></i>Add Doctor</a
    >
  </div>
  <div class="card-body">
    <table id="example1" class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>Full Name</th>
          <th>Phone</th>
          <th>Specialised in</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for doctor in doctors %}
        <tr>
         
          <td>
            <a
              href="#"
              style="color: #000"
              >{{ doctor.firstname }} {% if doctor.surname %} 
              {{ doctor.surname }} {% endif %} {% if doctor.middlename %} 
              {{ doctor.middlename }} {% endif %}</a
            >
          </td>
          <td>{% if doctor.phone %} {{ doctor.phone }} {% endif %}</td>
          <td>{% if doctor.specialised %} {{ doctor.specialised }} {% endif %}</td>
          <td>
            <a href="{% url 'patient:doctor_update' doctor.id %}"><i class="fas fa-pencil-alt text-primary"></i></a>
        </td>
        </tr>

        {% endfor %}
      </tbody>
      <tfoot>
        <tr>
          <th>Full Name</th>
          <th>Phone</th>
          <th>Specialised in</th>
          <th>Action</th>
        </tr>
      </tfoot>
    </table>
  </div>
  <div class="dataTables_paginate paging_simple_numbers ml-auto mr-4">
      {% if is_paginated %}
      <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="paginate_button page-item">
          <a class="page-link" href="?page={{page_obj.previous_page_number}}"
            >&laquo;</a
          >
        </li>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">&laquo;</a>
        </li>
        {% endif %} {% for i in paginator.page_range %} {% if page_obj.number == i%}
        <li class="paginate_button page-item active">
          <a class="page-link active">{{ i }}</a>
        </li>
        {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
        {% endif %} {% endfor %} {% if page_obj.has_next %}
        <li class="paginate_button page-item">
          <a href="?page={{page_obj.next_page_number}}" class="page-link"
            >&raquo;</a
          >
        </li>
        {% else %}
        <li class="page-item disabled">
          <a class="page-link">&raquo;</a>
        </li>
        {% endif %}
      </ul>
      {% endif %}
  
  </div>
  <!-- /.card-body -->
</div>
{% endblock %}

patient/templates/doctor/doc_update.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block title %} Add
Doctor {% endblock %} {% block content %}

<section class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1>Update Doctor Information</h1>
      </div>
    </div>
  </div>
</section>

<section class="content">
  <form action="" method="post">
    {% csrf_token %}
      <div class="col-md-6 mx-auto">
        <div class="card card-primary" style="min-height: 350px">
          <div class="card-header">
            <h3 class="card-title">Doctor Information</h3>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-sm-4">
                <div class="form-group">
                  {{ doctor_form.firstname | as_crispy_field }}
                </div>
              </div>
              <div class="col-sm-4">
                <div class="form-group">
                  {{ doctor_form.surname | as_crispy_field }}
                </div>
              </div>
              <div class="col-sm-4">
                <div class="form-group">
                  {{ doctor_form.middlename | as_crispy_field }}
                </div>
              </div>
            </div>
            
            <div class="row">
              <div class="col-12">
                <div class="form-group">
                  {{ doctor_form.phone | as_crispy_field }}
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-12">
                <div class="form-group">
                  {{ doctor_form.specialised | as_crispy_field }}
                </div>
              </div>
            </div>

          </div>
        </div>
        <div class="ml-auto w-25 text-right">
      <a href="{% url 'patient:doctor_list' %}" type="button" class="btn btn-secondary">Cancel</a>
      <input type="submit" value="Save" class="btn btn-success" />
    </div>
      </div>
      
    
  </form>
</section>

{% endblock %}