Clinic_Management_System/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('patient.urls')),
    path('', include('django.contrib.auth.urls'))
]

patient/urls.py
from django.urls import path
from . import views, views_doc

app_name = "patient"

urlpatterns = [
    path('', views.index, name="index"),
    # path('list', views.patient_list, name="list"),
    path('list/', views.PatientListView.as_view(), name="patient_list"),
    path('search', views.search, name="search"),
    # path('detail/<int:pk>', views.PatientDetailView.as_view(), name="patient_detail"),
    path('patients/detail/<int:patient_id>', views.patient_detail, name="patient_detail"),
    path('patients/add', views.patient_create, name="add"),
    path('patients/update/<int:patient_id>', views.patient_update, name="update"),
    path('patients/history/<int:patient_id>', views.patient_history, name="history"),
    # path('patients/update/<int:pk>', views.PatientUpdateView.as_view(), name="update"),
    path('patients/delete/<int:pk>', views.PatientDeleteView.as_view(), name="delete"),
    
    path('patients/select_appointment/', views.select_appointment, name="select_appointment"),
    path('patients/delete_appointment/', views.delete_appointment, name="delete_appointment"),
    path('appointment/', views.appointment_list, name="appointment"),
    path('patients/appointment/update/<int:appointment_id>', views.appointment_update, name="appointment_update"),
    
    path('patients/history/update/<int:history_id>', views.history_update, name="history_update"),
    
    path('doctors/list/', views_doc.DoctorListView.as_view(), name="doctor_list"),
    path('doctors/add', views_doc.doctor_create, name="doctor_add"),
    path('doctors/update/<int:doctor_id>', views_doc.doctor_update, name="doctor_update"),
    
    path('patients/history/pdf/<int:patient_id>', views.generatePdf, name="pdf_history"),
    # path('patients/history/pdf/<int:patient_id>', views.GeneratePdf.as_view(), name="pdf_history"),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="icon" href="{% static 'images/AdminLTELogo.png' %}">
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/all.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/toastr/toastr.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/adminlte.min.css' %}" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/mycss.css' %}">
    <script defer src="{% static 'js/appointment-script.js' %}"></script>

    <script defer type="text/javascript">
        getToken = (name) => {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        const csrftoken = getToken('csrftoken');
    </script>

</head>

<body class="hold-transition sidebar-mini">
    {% include 'partials/_message.html' %}
    <div class="wrapper">

        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <form class="form-inline ml-3" action="{% url 'patient:search' %}" method="get">
                <div class="input-group input-group-sm">
                    <input class="form-control form-control-navbar" name="search_term" type="search"
                        placeholder="Search" aria-label="Search" value="{{ search_term }}">
                    <div class="input-group-append">
                        <button class="btn btn-navbar" type="submit">
                            <i class="fas fa-search"></i>
                        </button>
                    </div>
                </div>
            </form>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Notifications Dropdown Menu -->
                
                <li class="nav-item">
                    {{user}} 
                    <a href="{% url 'logout' %}" class="">
                         <i class="fas fa-power-off"></i> Logout</a>
                </li>
            </ul>

        </nav>
        <!-- /.navbar -->

        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4 position-fixed">
            <!-- Brand Logo -->

            <div class="brand-text font-weight-light"
                style="color: rgba(255,255,255,.8); text-align: center; padding: 20px 0 !important; font-size: 1.22rem; background: #1d2125;">
                Dr. Haile Y/Berhane Internal Medicine Speciality Clinic</div>

            <!-- Sidebar -->
            <div class="sidebar">

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                        data-accordion="false">
                        <li class="nav-item">
                            <a href="{% url 'patient:index' %}" class="nav-link">
                                <i class="nav-icon fas fa-home"></i>
                                <p>
                                    Dashboard
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'patient:patient_list' %}" class="nav-link">
                                <i class="fas fa-list nav-icon"></i>
                                <p>Patients List</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'patient:add' %}" class="nav-link">
                                <i class="fas fa-user-plus nav-icon"></i>
                                <p>Add Patient</p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'patient:appointment' %}" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Appointments
                                    <span class="right badge badge-danger">{{base_appointment_today_count}}</span>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'patient:doctor_list' %}" class="nav-link">
                                <i class="fas fa-list nav-icon"></i>
                                <p>Doctors List</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'patient:doctor_add' %}" class="nav-link">
                                <i class="fas fa-user-md nav-icon"></i>
                                <p>Add Doctor</p>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
            <a class="nav-link text-light admin-link" target="_blank" href="{% url 'admin:index' %}">Admin</a>
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            {% block content %}

            {% endblock %}
        </div>

        <footer class="main-footer">
            Copyright &copy; CMS. All rights reserved.
        </footer>
    </div>

    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'plugins/sweetalert2/sweetalert2.min.js' %}"></script>
    <script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>
    <script src="{% static 'js/adminlte.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>

    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

    <script defer>
        $('#reservation').daterangepicker();
    </script>

</body>

</html>