Clinic_Management_System/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('patient.urls')),
    path('', include('django.contrib.auth.urls'))
]

patient/urls.py
from django.urls import path
from . import views, views_doc

app_name = "patient"

urlpatterns = [
    path('', views.index, name="index"),
    # path('list', views.patient_list, name="list"),
    path('list/', views.PatientListView.as_view(), name="patient_list"),
    path('search', views.search, name="search"),
    # path('detail/<int:pk>', views.PatientDetailView.as_view(), name="patient_detail"),
    path('patients/detail/<int:patient_id>', views.patient_detail, name="patient_detail"),
    path('patients/add', views.patient_create, name="add"),
    path('patients/update/<int:patient_id>', views.patient_update, name="update"),
    path('patients/history/<int:patient_id>', views.patient_history, name="history"),
    # path('patients/update/<int:pk>', views.PatientUpdateView.as_view(), name="update"),
    path('patients/delete/<int:pk>', views.PatientDeleteView.as_view(), name="delete"),
    
    path('patients/select_appointment/', views.select_appointment, name="select_appointment"),
    path('patients/delete_appointment/', views.delete_appointment, name="delete_appointment"),
    path('appointment/', views.appointment_list, name="appointment"),
    path('patients/appointment/update/<int:appointment_id>', views.appointment_update, name="appointment_update"),
    
    path('patients/history/update/<int:history_id>', views.history_update, name="history_update"),
    
    path('doctors/list/', views_doc.DoctorListView.as_view(), name="doctor_list"),
    path('doctors/add', views_doc.doctor_create, name="doctor_add"),
    path('doctors/update/<int:doctor_id>', views_doc.doctor_update, name="doctor_update"),
    
    path('patients/history/pdf/<int:patient_id>', views.generatePdf, name="pdf_history"),
    # path('patients/history/pdf/<int:patient_id>', views.GeneratePdf.as_view(), name="pdf_history"),

]

patient/forms.py
from django import forms
from datetime import datetime, timedelta
from .models import CHOICES, SUB_CITY_CHOICES, Patient, Appointment, History, Doctor
from django.forms.fields import Field
from crispy_forms.layout import Layout
from crispy_forms.helper import FormHelper


class DateInput(forms.DateInput):
    input_type = 'date'


class PatientForm(forms.ModelForm):
    firstname = forms.CharField(label="First Name")
    surname = forms.CharField(label="Sur Name", required=False)
    middlename = forms.CharField(label="Middle Name", required=False)
    gender = forms.ChoiceField(choices=CHOICES, required=False)
    age = forms.FloatField(label="Age", required=False)
    phone = forms.IntegerField(label="Phone", required=False)

    kebele = forms.IntegerField(label="Kebele", required=False)
    woreda = forms.IntegerField(label="Woreda", required=False)
    sub_city = forms.ChoiceField(label="Subcity",
                                 choices=SUB_CITY_CHOICES,
                                 required=False)

    class Meta:
        model = Patient
        fields = [
            'firstname', 'surname', 'middlename', 'gender', 'age', 'phone',
            'kebele', 'woreda', 'sub_city'
        ]

    def clean(self):
        super(PatientForm, self).clean()

        age = self.cleaned_data.get('age')
        kebele = self.cleaned_data.get('kebele')
        woreda = self.cleaned_data.get('woreda')
        phone = self.cleaned_data.get('phone')

        if age != None and age < 0:
            self._errors['age'] = self.error_class(['Minimum Age must be 0'])
        if kebele != None and kebele < 1:
            self._errors['kebele'] = self.error_class(
                ['Kebele must be greater than 1'])
        if woreda != None and woreda < 1:
            self._errors['woreda'] = self.error_class(
                ['Woreda must be greater than 1'])

        if phone != None and phone < 1:
            self._errors['phone'] = self.error_class(
                ['Phone Number is not valid'])


class HistoryForm(forms.ModelForm):
    history = forms.CharField(label="History and Physical Examination",
                              required=False,
                              widget=forms.Textarea(attrs={
                                  'rows': 5,
                                  'cols': 40
                              }))
    doctor = forms.ChoiceField(
        label="Doctor",
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = History
        fields = ['history']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['doctor'].choices = [(doctor.id,
                                          f'{doctor.firstname} {doctor.surname}')
                                         for doctor in Doctor.objects.all()]


class AppointmentForm(forms.ModelForm):
    # patient = forms.CharField(label="First Name")

    date = forms.DateField(
        label="Appointment",
        widget=DateInput(
            attrs={"min": datetime.now().date().strftime("%Y-%m-%d"), 'id':'assignedDoctor'}),
        required=False)

    class Meta:
        model = Appointment
        fields = ['date', 'doctor']


class DoctorForm(forms.ModelForm):
    firstname = forms.CharField(label="First Name")
    surname = forms.CharField(label="Sur Name", required=False)
    middlename = forms.CharField(label="Middle Name", required=False)
    specialised = forms.CharField(label="Specialised in", required=False)

    phone = forms.IntegerField(label="Phone", required=False)


    class Meta:
        model = Doctor
        fields = [
            'firstname', 'surname', 'middlename', 'phone', 'specialised'
        ]

    # appointment = forms.DateField(
    #     label="Appointment",
    #     widget=DateInput(
    #         attrs={"min": datetime.now().date().strftime("%Y-%m-%d")}),
    #     required=False)

patient/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse, redirect, get_object_or_404
from django.http import JsonResponse, HttpResponse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
import json
from .forms import PatientForm, AppointmentForm, HistoryForm
from .models import Patient, Appointment, History, Doctor
import datetime
from django.http import HttpResponse
from django.views.generic import View

from .utils import render_to_pdf


@login_required()
def index(request):
    return render(request, 'patient/index.html', {})


class PatientListView(LoginRequiredMixin, ListView):
    template_name = 'patient/list.html'
    model = Patient
    context_object_name = 'patients'
    paginate_by = 100


class PatientDetailView(LoginRequiredMixin, DetailView):
    template_name = 'patient/detail.html'
    model = Patient
    context_object_name = 'patient'


@login_required()
def patient_detail(request, patient_id):
    return render(
        request, 'patient/detail.html', {
            'patient': Patient.objects.get(pk=patient_id),
            'histories': History.objects.filter(patient=patient_id),
            'doctors': Doctor.objects.all(),
            'appointments': Appointment.objects.filter(patient=patient_id)
        })


@login_required()
def search(request):
    if request.GET:
        search_term = request.GET['search_term']
        context = {
            "search_term":
            search_term,
            "patients":
            Patient.objects.filter(
                Q(card_number__icontains=search_term)
                | Q(firstname__icontains=search_term)
                | Q(surname__icontains=search_term)
                | Q(middlename__icontains=search_term)
                | Q(gender__icontains=search_term)
                | Q(phone__icontains=search_term)
                | Q(created_date__icontains=search_term)
                # Q(appointment__icontains=search_term)
            )
        }
        if not search_term == "":
            return render(request, 'patient/search.html', context)
        else:
            return HttpResponseRedirect(reverse('patient:index'))


@login_required()
def patient_create(request):
    if request.method == 'POST':
        patient_form = PatientForm(request.POST)

        if patient_form.is_valid():
            firstname = patient_form.cleaned_data['firstname']
            surname = patient_form.cleaned_data['surname']
            middlename = patient_form.cleaned_data['middlename']
            gender = patient_form.cleaned_data['gender']
            age = patient_form.cleaned_data['age']
            phone = patient_form.cleaned_data['phone']

            kebele = patient_form.cleaned_data['kebele']
            woreda = patient_form.cleaned_data['woreda']
            sub_city = patient_form.cleaned_data['sub_city']

            patient = Patient.objects.create(firstname=firstname,
                                             surname=surname,
                                             middlename=middlename,
                                             gender=gender,
                                             age=age,
                                             phone=phone,
                                             kebele=kebele,
                                             woreda=woreda,
                                             sub_city=sub_city,
                                             created_by=request.user,
                                             updated_by=request.user)

            patient.save()

            messages.add_message(request, messages.SUCCESS,
                                 'Patient added successfully!')

            return HttpResponseRedirect(reverse('patient:patient_list'))
        else:
            return render(request, 'patient/add.html',
                          {"patient_form": patient_form})
    return render(request, 'patient/add.html', {"patient_form": PatientForm()})


@login_required()
def patient_update(request, patient_id):
    patient = get_object_or_404(Patient, pk=patient_id)
    patient_form = PatientForm(request.POST or None, instance=patient)

    if patient_form.is_valid():
        patient.save()

        messages.add_message(request, messages.SUCCESS,
                             'Patient data updated successfully!')

        return HttpResponseRedirect(reverse('patient:patient_list'))
    else:
        return render(request, 'patient/add.html',
                      {"patient_form": patient_form})
    return render(request, 'patient/update.html',
                  {"patient_form": patient_form})


class PatientUpdateView(LoginRequiredMixin, UpdateView):
    model = Patient
    template_name = 'patient/update.html'
    fields = ['firstname', 'surname', 'middlename', 'age', 'gender', 'phone']

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.updated_by = self.request.user
        instance.save()
        messages.success(self.request, 'Patient data updated successfully!')
        return redirect('patient:patient_detail', instance.pk)


class PatientDeleteView(LoginRequiredMixin, DeleteView):
    model = Patient
    template_name = 'patient/delete.html'
    success_url = '../list/'


@login_required()
def patient_history(request, patient_id):
    if request.method == 'POST':
        history_form = HistoryForm(request.POST)

        if history_form.is_valid():
            history = history_form.cleaned_data['history']
            doctor = history_form.cleaned_data['doctor']

            history = History.objects.create(
                history=history,
                doctor=Doctor.objects.get(pk=doctor),
                patient=Patient.objects.get(pk=patient_id))

            history.save()

            messages.add_message(request, messages.SUCCESS,
                                 'History added successfully!')

            return HttpResponseRedirect(
                reverse('patient:patient_detail', args=(patient_id, )))
        else:
            return render(request, 'patient/history.html',
                          {"history_form": history_form})

    return render(request, 'patient/history.html',
                  {"history_form": HistoryForm()})


@login_required()
def history_update(request, history_id):
    history = get_object_or_404(History, pk=history_id)
    history_form = HistoryForm(request.POST or None, instance=history)

    if history_form.is_valid():
        history.save()

        messages.add_message(request, messages.SUCCESS,
                             'History updated successfully!')

        return HttpResponseRedirect(
            reverse('patient:patient_detail', args=(history.patient.id, )))
    else:
        return render(request, 'patient/history.html',
                      {"history_form": history_form})
    return render(request, 'patient/history.html',
                  {"history_form": history_form})


@login_required()
def appointment_update(request, appointment_id):
    appointment = get_object_or_404(Appointment, pk=appointment_id)
    appointment_form = AppointmentForm(request.POST or None,
                                       instance=appointment)

    if appointment_form.is_valid():
        appointment.save()

        messages.add_message(request, messages.SUCCESS,
                             'Appointment updated successfully!')

        return HttpResponseRedirect(
            reverse('patient:patient_detail', args=(appointment.patient.id, )))
    else:
        return render(request, 'patient/update_appointment.html',
                      {"appointment_form": appointment_form})
    return render(request, 'patient/update_appointment.html',
                  {"appointment_form": appointment_form})


@login_required()
def appointment_list(request):
    return render(
        request, 'patient/appointment.html', {
            "appointment":
            Appointment.objects.all().count(),
            "appointment_today":
            Appointment.objects.filter(date=datetime.date.today()),
            "appointment_tomorrow":
            Appointment.objects.filter(date=datetime.date.today() +
                                       datetime.timedelta(days=1))
        })


@login_required()
def select_appointment(request):
    data = json.loads(request.body)
    patient_id = data["patientId"]
    appointment_date = data["appointmentDate"]
    assigned_doctor = data["assignedDoctor"]
    action = data["action"]

    Appointment.objects.get_or_create(patient=Patient(id=patient_id),
                                      date=appointment_date,
                                      doctor=Doctor(id=assigned_doctor))
    return JsonResponse(
        f'Appointment Booked for {Patient.objects.get(pk=patient_id).firstname} {Patient.objects.get(pk=patient_id).surname}',
        safe=False)


@login_required()
def delete_appointment(request):
    data = json.loads(request.body)
    print('dfdfdf')
    appointment_id = data["appointmentId"]
    print(appointment_id)
    action = data["action"]

    Appointment.objects.filter(id=appointment_id).delete()
    
    return JsonResponse(
        f'Appointment Deleted',
        safe=False)


# def appointment_delete(request, appointment_id):
#     appointment = get_object_or_404(Appointment, id=appointment_id)
#     appointment.delete()
    

def generatePdf(request, patient_id, *args, **kwargs):
    data = {
        'date': datetime.date.today(),
        'patient': Patient.objects.get(pk=patient_id),
        'histories': History.objects.filter(patient=patient_id),
    }
    pdf = render_to_pdf('pdf/pdf_history.html', data)
    return HttpResponse(pdf, content_type='application/pdf')

patient/templates/patient/delete.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}
    Delete Patient
{% endblock %}

{% block content %}

    <section class="content">
        <div class="card card-warning card-outline">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-edit"></i>
                    Toastr Examples
                </h3>
            </div>
            <div class="card-body">
                <button type="button" class="btn btn-success toastrDefaultSuccess">
                    Launch Success Toast
                </button>
                <button type="button" class="btn btn-info toastrDefaultInfo">
                    Launch Info Toast
                </button>
                <button type="button" class="btn btn-danger toastrDefaultError">
                    Launch Error Toast
                </button>
                <button type="button" class="btn btn-warning toastrDefaultWarning">
                    Launch Warning Toast
                </button>
                <div class="text-muted mt-3">
                    For more examples look at <a href="https://codeseven.github.io/toastr/">https://codeseven.github.io/toastr/</a>
                </div>
            </div>
            <!-- /.card -->
        </div>
    </section>

{% endblock %}

patient/templates/patient/detail.html
{% extends 'base.html' %} {% load static %} {% block title %} Patient Detail {% endblock %} {% block content %}

<div class="wrapper">
  <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-4">
          <h1 style="padding-bottom: 0.5rem">Details</h1>
          <a href="{% url 'patient:patient_list' %}">
            <strong
              ><i class="fas fa-angle-double-left"></i> Back to List</strong
            >
          </a>
        </div>
        <div class="col-sm-8">
          <div class="breadcrumb float-sm-right">
            <button
              type="button"
              class="btn btn-sm btn-warning text-white mr-4"
              data-toggle="modal"
              data-target="#modal-default"
            >
              <i class="far fa-calendar mr-2"></i>Add Appointment
            </button>
            <a
              href="{% url 'patient:update' patient.id %}"
              class="btn btn-sm btn-primary text-white"
              ><i class="far fa-edit mr-2"></i>Edit</a
            >
            <a
              href="{% url 'patient:history' patient.id %}"
              class="btn btn-sm btn-success text-white ml-3"
              >Add History & Examination</a
            >
            <a
              href="{% url 'patient:pdf_history' patient.id %}"
              target="_blank"
              class="btn btn-sm btn-outline-info ml-3"
              >Print</a
            >
          </div>
        </div>
      </div>
    </div>
    <!-- /.container-fluid -->
  </section>

  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-4">
          <div class="card card-primary card-outline">
            <div class="card-body box-profile">
              <div class="text-center"></div>

              <h3 class="profile-username text-center">
                <strong
                  >{{ patient.firstname }} {{ patient.surname }} 
                  {{ patient.middlename }}</strong
                >
              </h3>

              <p class="text-muted text-center">{{ patient.card_number }}</p>

              <div class="card-body">
                <table class="table">
                  <thead>
                    <tr>
                      <th>
                        <strong
                          ><i class="fas fa-calendar-plus mr-1"></i>Age</strong
                        >
                      </th>
                      <th>
                        <strong
                          ><i class="fas fa-venus-mars mr-1"></i>Gender</strong
                        >
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>
                        <p class="text-muted ml-3">{{ patient.age }}</p>
                      </td>
                      <td>
                        <p class="text-muted ml-3">{{ patient.gender }}</p>
                      </td>
                    </tr>
                  </tbody>
                </table>

                <hr />

                <strong><i class="fas fa-phone mr-2"></i>Phone</strong>

                <p class="text-muted ml-3">{{ patient.phone }}</p>

                <hr />

                <strong
                  ><i class="fas fa-map-marker-alt mr-2"></i>Address</strong
                >

                <p class="text-muted ml-3">Kebele: {{ patient.kebele }}</p>
                <p class="text-muted ml-3">Woreda: {{ patient.woreda }}</p>
                <p class="text-muted ml-3">Subcity: {{ patient.sub_city }}</p>

                <hr />

                <strong
                  ><i class="fas fa-calendar-alt mr-2"></i> First Visit
                  Date</strong
                >

                <p class="text-muted ml-3">{{ patient.created_date }}</p>

                
                <hr />
       
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="card history-display">
            <div class="card-header p-2">
              <ul class="nav nav-pills">
                <li class="nav-item nav-link">History & Examination</li>
              </ul>
            </div>
            <div class="card-body">
              <div class="" id="activity">
               {% for history in histories %}
                <div class="post">
                <input type="hidden" value="{{history.id}}"/>
                  <div class="d-flex">
                  <div class="user-block">
                    <span class="username text-primary" style="margin-left: 0"
                      >{{history.date}}</span
                    >
                    <span class="description" style="margin-left: 0"
                      >By Dr. {{history.doctor.firstname}} {{history.doctor.surname}}</span
                    >
                  </div>
                  <a href="{% url 'patient:history_update' history.id %}"><i class="fas fa-pencil-alt text-secondary sm"></i></a>
                  </div>
                  <p>
                    {{history.history}}
                  </p>
                </div>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
        <div class="card appointment-display">
              <div class="card-header p-2">
              <ul class="nav nav-pills">
                <li class="nav-item nav-link">Appointments</li>
              </ul>
            </div>
              <!-- /.card-header -->
              <div class="card-body p-0">
                <table class="table">
                  <thead>
                    <tr>
                      <th>Date</th>
                      <th>Assigned Doctor</th>
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for appointment in appointments %}
                  <tr>
                      <td>{{ appointment.date}}</td>
                      <td>{{appointment.doctor}}</td>
                      <td>
                        <a href="{% url 'patient:appointment_update' appointment.id %}"><i class="fas fa-pencil-alt text-secondary sm"></i></a>
                      </td>
                    </tr>
                  {% endfor %}
                    
                    
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
        </div>
      </div>
    </div>
  </section>
</div>

<div class="modal fade" id="modal-default">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Book Appointment</h4>
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="" return="false">
        {% csrf_token %}
        <div class="modal-body">
          <p>
            <strong>Card Number: </strong> {{ patient.card_number }} <br>
            <strong>Patient Name: </strong> {{ patient.firstname }} {{ patient.surname}}
          </p>
          <p>
            Date:
            <input
              type="date"
              class="form-control datetimepicker-input"
              id="appointment_date"
            />
          </p>
          <p>
            Assign Doctor:
            <select
              class="form-control"
              name="doctor"
              id="assignedDoctor">
              {% for doctor in doctors %}
                <option value="{{doctor.id}}">{{doctor.firstname}} {{doctor.surname}}</option>
              {% endfor %}%}
            </select>
          </p>
        </div>
        <div class="modal-footer justify-content-between">
          <button type="button" class="btn btn-default" data-dismiss="modal">
            Close
          </button>
          <a
            data-appointment="{{ patient.id }}"
            data-action="appointment"
            class="btn btn-success select-appointment text-white"
            data-dismiss="modal"
            >Save</a
          >
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

patient/templates/patient/index.html
{% extends 'base.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <div class="wrapper">

        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Dashboard</h1>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Small boxes (Stat box) -->
                <div class="row">
                    <div class="col-lg-3 col-6">
                        <!-- small box -->
                        <div class="small-box bg-info">
                            <div class="inner">
                                <h3>{% if base_patient_count != 0 %}{{base_patient_count}}{% else %} 0 {%endif%}</h3>

                                <p>Patients</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-bag"></i>
                            </div>
                            <a href="{% url 'patient:patient_list' %}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <!-- ./col -->
                    <div class="col-lg-3 col-6">
                        <!-- small box -->
                        <div class="small-box bg-danger">
                            <div class="inner">
                                <h3>{% if base_appointment_today_count != 0 %}{{base_appointment_today_count}}{% else %} 0 {%endif%}</h3>

                                <p>Today's Appointment</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-pie-graph"></i>
                            </div>
                            <a href="{% url 'patient:appointment' %}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                        </div>

                    </div>
                    <!-- ./col -->
                    <div class="col-lg-3 col-6">
                        <!-- small box -->
                        <div class="small-box bg-warning">
                            <div class="inner">
                                <h3>{{base_patient_today_count}}</h3>

                                <p>Patient Added Today</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-person-add"></i>
                            </div>
                            <a href="{% url 'patient:patient_list' %}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                        </div>
                    </div>
                    <!-- ./col -->
                    <div class="col-lg-3 col-6">
                        <!-- small box -->
                        <div class="small-box bg-success">
                            <div class="inner">
                                <h3>{{base_doctor_count}}</h3>

                                <p>Doctors</p>
                            </div>
                            <div class="icon">
                                <i class="ion ion-stats-bars"></i>
                            </div>
                            <a href="{% url 'patient:doctor_list' %}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                        </div>

                    </div>
                    <!-- ./col -->
                </div>
                <!-- /.row -->
                <!-- Main row -->
                <div class="row">
                    <!-- Left col -->
                    
                    <!-- /.Left col -->
                    <!-- right col (We are only adding the ID to make the widgets sortable)-->
                    <section class="col-lg-5 connectedSortable">

                        <!-- Map card -->
                       
                        <!-- /.card -->

                    </section>
                    <!-- right col -->
                </div>
                <!-- /.row (main row) -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
    </div>

{% endblock %}

patient/templates/patient/print.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Title</title>
        <style type="text/css">
            body {
                font-weight: 200;
                font-size: 14px;
            }
            .header {
                font-size: 20px;
                font-weight: 100;
                text-align: center;
                color: #007cae;
            }
            .title {
                font-size: 22px;
                font-weight: 100;
               /* text-align: right;*/
               padding: 10px 20px 0px 20px;  
            }
            .title span {
                color: #007cae;
            }
            .details {
                padding: 10px 20px 0px 20px;
                text-align: left !important;
                /*margin-left: 40%;*/
            }
            .hrItem {
                border: none;
                height: 1px;
                /* Set the hr color */
                color: #333; /* old IE */
                background-color: #fff; /* Modern Browsers */
            }
        </style>
    </head>
    <body>
        <div class='wrapper'>
            <div class='header'>
                <p class='title'>Invoice # </p>
            </div>
        <div>
        <div class='details'>
            Bill to: <br/>
            Amount:  <br/>
            Date: 
            <hr class='hrItem' />
        </div>
    </div>
    </body>
</html>